# environment.yml
name: myenv
channels:
  - roebel
  - jwwatts
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pysndfile
  - ffmpeg
  - django>=5.0
  - celery
  - redis-py
  - psycopg2
  - gunicorn
  - tensorflow
  - channels
  - channels-redis
  - daphne
  - redis
